catastrophewebsite/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5
from .routes import main_blueprint


def create_app():
    """Create and configure an instance of the Flask application."""
    app = Flask(__name__)
    Bootstrap5(app)

    app.register_blueprint(main_blueprint)

    return app

catastrophewebsite/routes.py
from flask import Blueprint, render_template

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def home():
    """Render the home page."""
    return render_template("index.html.j2")


@main_blueprint.route("/roadmap")
def roadmap():
    """Render the roadmap page."""
    return render_template("roadmap.html.j2")


@main_blueprint.route("/about")
def about():
    """Render the about page."""
    return render_template("about.html.j2")


@main_blueprint.route("/contact")
def contact():
    """Render the contact page."""
    return render_template("contact.html.j2")

catastrophewebsite/templates/about.html.j2
{% extends 'base.html.j2' %}

catastrophewebsite/templates/base.html.j2
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}chloemathews.net{% endblock %}</title>
    {{ bootstrap.load_css() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">0xChloe</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-left" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.roadmap') }}">Roadmap</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                    </li>
                </ul>
            </div>
        </div>

    </nav>

    <div class="container-fluid mt-5">
        {% block content %}
        {% endblock %}
    </div>
    {{ bootstrap.load_js() }}
</body>

</html>

catastrophewebsite/templates/contact.html.j2
{% extends 'base.html.j2' %}

{% block title %}Contact - Chloe Mathews{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Contact Me</h1>
    <div class="row g-4">
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Bluesky</h5>
                    <p class="card-text">Follow me on Bluesky</p>
                    <a target="_blank" rel="noopener noreferrer" href="https://bsky.app/profile/0xchloe.bsky.social"
                        class="btn btn-primary">Visit Bluesky</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Twitter</h5>
                    <p class="card-text">Tweet at me @0xChlxe.</p>
                    <a target="_blank" rel="noopener noreferrer" href="https://twitter.com/0xChlxe"
                        class="btn btn-primary">Visit Twitter</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">GitHub</h5>
                    <p class="card-text">Check out my projects on GitHub.</p>
                    <a target="_blank" rel="noopener noreferrer" href="https://github.com/cmathews393"
                        class="btn btn-primary">Visit GitHub</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Email</h5>
                    <p class="card-text">Send me an email for inquiries.</p>
                    <a target="_blank" rel="noopener noreferrer" href="mailto:chloe@chloemathews.net"
                        class="btn btn-primary">Send Email</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catastrophewebsite/templates/index.html.j2
{% extends 'base.html.j2' %}

{% block title %}Home - Chloe Mathews{% endblock %}

{% block content %}
<div class="container mt-5 text-center">
    <h1 class="display-4 text-primary mb-4">Welcome to chloemathews.net</h1>
    <p class="lead">Welcome to my homepage. Check out the pages below for more about me!</p>
    <p class="text-muted">A bit about me: I am a Python dev with 5 years experience as a systems and network
        administrator. I work on a few self-hosting tools in my free time, mostly my sync tool for Spotify/Plex, and
        some WIP tools like Plex Playlist Manager. See my <a href="/roadmap">roadmap</a> for more info on upcoming
        projects!</p>
    <a href="#about" class="btn btn-primary">Learn More About Me</a>
</div>
{% endblock %}

catastrophewebsite/templates/roadmap.html.j2
{% extends 'base.html.j2' %}

{% block title %}Roadmap - Chloe Mathews{% endblock %}


{% block content %}
<div class="container-fluid mt-5">
    <h1 class="text-center mb-4">My Projects</h1>
    <iframe src="https://v2-embednotion.com/439a05b19318479fa95cba937e2e6a98" class="full-height-iframe"></iframe>
</div>
{% endblock %}